"""v54.1 — tests for the fixes made after direct user feedback on the
Strategies-page table: the four previously-missing strategies (orb,
vwap_pullback, ema_mtf, momentum_buy), the backtest-approval-gate
detection that must apply to three of those four but NOT momentum_buy,
and that a broken/incomplete analysis dict degrades gracefully rather
than crashing the endpoint.

Run:  python3 test_strategies_table_v2.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fastapi.testclient import TestClient
import app
import agents
import backtester

results = []


def check(label, cond, detail=""):
    results.append((label, bool(cond)))
    print(("  PASS  " if cond else "  FAIL  ") + label +
          (f"   [{detail}]" if detail else ""))


client = TestClient(app.app)
SYM = "NIFTY"

full_analysis = {
    "symbol": SYM, "spot": 23800, "atm": 23800,
    "strikes": [{"strike": 23800, "ce": {"ltp": 120, "volume": 10, "state": "x"},
                "pe": {"ltp": 115, "volume": 10, "state": "x"}}],
    "signal_lines": {"R": [], "S": []},
    "bias": "BULLISH", "risk_meter": 30, "momentum": {"trend": "rising", "pct_15m": 0.2},
    "support": [23700], "resistance": [23900], "max_pain": 23800,
    "confidence": 78, "pcr_oi": 0.9,
}


def seed_candles():
    import math
    closes = [23800 - i * 2 + math.sin(i / 5) * 90 for i in range(60)]
    c1 = [{"time": 1753500000 + i * 60, "open": x, "high": x + 2, "low": x - 2,
          "close": x} for i, x in enumerate(closes)]
    app.pilot.bus.set(f"pa_candles:{SYM}", {"c1": c1, "c5": c1[::5], "c15": c1[::15],
                                            "ts": 0})


print("1) all four previously-missing strategies now appear in the payload")
app.pilot.bus.set(f"analysis:{SYM}", full_analysis)
seed_candles()
app.pilot.bus.set(f"regime:{SYM}", None)
d = client.get(f"/api/strategies/{SYM}").json()
check("no error", d.get("error") is None, str(d.get("error")))
check("pa_previews includes orb/vwap_pullback/ema_mtf (superset check, "
     "not exact match — new PA strategies like momentum_confluence "
     "are EXPECTED to also appear here, not treated as a regression)",
      {"orb", "vwap_pullback", "ema_mtf"} <= set(d.get("pa_previews", {}).keys()),
      str(d.get("pa_previews")))
check("momentum_preview present and evaluated (not an error)",
      d.get("momentum_preview", {}).get("eligible") is not None,
      str(d.get("momentum_preview")))
check("current_positions includes all 4 new keys",
      {"orb", "vwap_pullback", "ema_mtf", "momentum_buy"} <=
      set(d.get("current_positions", {}).keys()))

print("\n2) backtest-approval gate applies to orb/vwap_pullback/ema_mtf, "
      "confirmed present as fields")
for name in ("orb", "vwap_pullback", "ema_mtf"):
    pv = d["pa_previews"][name]
    check(f"'{name}' preview carries live_enabled/manually_disabled fields",
          "live_enabled" in pv and "manually_disabled" in pv, str(pv))

print("\n3) the gate fields actually reflect the persisted version file "
      "(not hardcoded False)")
v = backtester.load_versions()
_prior = v.get("orb", {}).get("symbols", {}).get(SYM)
v.setdefault("orb", {}).setdefault("symbols", {})[SYM] = {
    "active": 1, "versions": [{"v": 1, "params": {}, "created": "x"}],
    "live_enabled": True, "manually_disabled": False}
backtester.save_versions(v)
d2 = client.get(f"/api/strategies/{SYM}").json()
check("orb live_enabled reflects the version file",
      d2["pa_previews"]["orb"]["live_enabled"] is True)
# restore
if _prior is None:
    v["orb"]["symbols"].pop(SYM, None)
else:
    v["orb"]["symbols"][SYM] = _prior
backtester.save_versions(v)
check("orb version entry restored exactly",
      backtester.load_versions().get("orb", {}).get("symbols", {}).get(SYM) == _prior)

print("\n4) momentum_buy has NO backtest-approval gate (confirmed by "
      "source inspection, not just absence in this payload)")
src = open("agents.py").read()
# momentum_buy is generated by StrategyAgent; confirm StrategyAgent's
# cycle() does not reference is_live_enabled anywhere in this file
# except the two PA/spread call sites already known.
count = src.count("backtester.is_live_enabled(")
check("backtester.is_live_enabled( is CALLED exactly twice in agents.py (spread loop "
      "+ PriceActionAgent) — momentum_buy/StrategyAgent has no third call",
      count == 2, f"found {count} occurrences")

print("\n5) an incomplete analysis dict degrades gracefully, doesn't 500")
app.pilot.bus.set(f"analysis:{SYM}", {
    "symbol": SYM, "spot": 23800, "atm": 23800,
    "strikes": [{"strike": 23800, "ce": {"ltp": 120}, "pe": {"ltp": 115}}],
    "signal_lines": {"R": [], "S": []}})   # missing confidence/bias/etc.
r = client.get(f"/api/strategies/{SYM}")
check("endpoint still returns 200 with an incomplete analysis dict",
      r.status_code == 200, str(r.status_code))
d3 = r.json()
check("momentum_preview reports the error instead of crashing the page",
      d3.get("momentum_preview", {}).get("eligible") is None and
      "error" in str(d3.get("momentum_preview", {}).get("why", "")),
      str(d3.get("momentum_preview")))
check("pa_previews/current_positions still present despite the momentum error",
      "pa_previews" in d3 and "current_positions" in d3)

print("\n6) Configure-modal routing list matches backtester's own ALL_NAMES "
      "(orb/vwap_pullback/ema_mtf/momentum_buy get the rich version modal)")
h = open("static/dashboard.html").read()
i = h.index("const VERSIONED=")
line = h[i:h.index("\n", i)]
for name in ("bull_put_spread", "bear_call_spread", "orb", "vwap_pullback",
            "ema_mtf", "momentum_buy"):
    check(f"'{name}' routes to the version-history modal", f'"{name}"' in line,
          line[:80])

print("\n" + "=" * 60)
failed = [l for l, ok in results if not ok]
if failed:
    print(f"FAIL ({len(failed)}/{len(results)}):")
    for f in failed:
        print("  - " + f)
    sys.exit(1)
print(f"PASS — all {len(results)} checks")
